gestionproyecto/api/urls.py
from django.urls import path
from .views import (ClienteList, InversionistaList,
                    ProyectoView, TipoUsuario, ProyectoClienteView)
app_name = 'api'
urlpatterns = [
    path('clientes', ClienteList.as_view()),
    path('clientes/<int:pk>/', ClienteList.as_view()),
    path('inversionistas', InversionistaList.as_view()),
    path('inversionistas/<int:pk>/', InversionistaList.as_view()),
    path('proyectos', ProyectoView.as_view()),
    path('proyectos/clientes', ProyectoClienteView.as_view()),
    path('me', TipoUsuario.as_view()),
]

gestionproyecto/dashboard/urls.py
from django.urls import path
from .views import (index,
                    CrearCliente,
                    CrearInversionista,
                    InversionistaList,
                    ClienteList, ClienteDetail,
                    InversionistaDetail, InversionistaUpdate,
                    ClienteUpdate, InversionistaDelete,
                    ClienteDelete)
app_name = 'dashboard'
urlpatterns = [
    #path('register', register, name='register'),
    path('', index, name='inicio'),
    path('cliente-add/', CrearCliente.as_view(), name='cliente_add'),
    path('cliente-list', ClienteList.as_view(), name='cliente_list'),
    path('cliente/<int:pk>/', ClienteDetail.as_view(), name='cliente_detail'),
    path('edit/cliente/<int:pk>/', ClienteUpdate.as_view(), name='cliente_update'),
    path('delete/cliente/<int:pk>/', ClienteDelete.as_view(), name='cliente_delete'),
    path('inversionista-add', CrearInversionista.as_view(), name='inver_add'),
    path('inversionista-list', InversionistaList.as_view(), name='inver_list'),
    path('inver/<int:pk>/', InversionistaDetail.as_view(), name='inver_detail'),
    path('delete/inver/<int:pk>/', InversionistaDelete.as_view(), name='inver_delete'),
    path('edit/inver/<int:pk>/', InversionistaUpdate.as_view(), name='inver_update'),
]

gestionproyecto/gestionproyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('users', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('proyectos/', include('proyectos.urls')),
    path('api/login', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify', TokenVerifyView.as_view(), name='token_verify'),
    path('api/', include('api.urls')),
    path('', include('users.urls')),
]

gestionproyecto/dashboard/models.py
from django.db import models
from django.shortcuts import reverse


class Empresa(models.Model):
    nombre_empresa = models.CharField(max_length=50)
    nit_empresa = models.CharField(max_length=50)
    tel_empresa = models.CharField(max_length=10)
    direc_empresa = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre_empresa


class Cliente(models.Model):
    nombre_cliente = models.CharField(max_length=50)
    nit_cliente = models.CharField(max_length=50)
    tel_cliente = models.CharField(max_length=11)
    direc_cliente = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('dashboard:cliente_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.nombre_cliente


class Inversionista(models.Model):
    opciones = (
        (1, 'Inversionista'),
        (2, 'Banco')
    )

    nombre = models.CharField(max_length=50)
    nit = models.CharField(max_length=50)
    telefono = models.CharField(max_length=10)
    direccion = models.CharField(max_length=50)
    tipo_inver = models.IntegerField(choices=opciones, default=1)

    def get_absolute_url(self):
        return reverse('dashboard:inver_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.nombre

gestionproyecto/dashboard/forms.py
from django import forms
from .models import Cliente, Inversionista
from django.contrib.auth.models import User


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ('nombre_cliente', 'nit_cliente',
                  'tel_cliente', 'direc_cliente')


class InversionistaForm(forms.ModelForm):
    class Meta:
        model = Inversionista
        fields = ('nombre', 'nit',
                  'telefono', 'direccion', 'tipo_inver')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password', 'email')
        widgets = {
            'password': forms.PasswordInput()
        }

gestionproyecto/dashboard/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (View, ListView, DetailView,
                                  UpdateView, DeleteView)
from .forms import ClienteForm, UserForm, InversionistaForm
from .models import Inversionista, Cliente
from users.models import ClienteUser, InversionistaUser

@login_required()
def index(request):
    nombre = request.user.username
    print(request.user.has_perm('users.add_empresauser'))
    return render(request, 'dashboard/dashboard.html', {'nombre': nombre})


class CrearCliente(LoginRequiredMixin, View):

    def get(self, request):
        form_cliente = ClienteForm()
        form_user = UserForm()
        context = {'form_user': form_user, 'form_cli': form_cliente}
        return render(request, 'dashboard/cliente_form.html', context)

    @staticmethod
    def post(request):
        form_cliente = ClienteForm(request.POST)
        form_user = UserForm(request.POST)
        if form_cliente.is_valid() and form_user.is_valid():
            cliente = form_cliente.save()
            user = form_user.save(commit=False)
            user.set_password(user.password)
            user.save()
            ClienteUser.objects.create(user=user, cliente=cliente)
            return redirect('dashboard:inicio')


class CrearInversionista(LoginRequiredMixin, View):

    def get(self, request):
        form_inversion = InversionistaForm()
        form_user = UserForm()
        context = {'form_user': form_user, 'form_inver': form_inversion}
        return render(request, 'dashboard/iversionista_form.html', context)

    @staticmethod
    def post(request):
        form_inversion = InversionistaForm(request.POST)
        form_user = UserForm(request.POST)
        if form_inversion.is_valid() and form_user.is_valid():
            inversionista = form_inversion.save()
            user = form_user.save(commit=False)
            user.set_password(user.password)
            user.save()
            InversionistaUser.objects.create(user=user, inversionista=inversionista)
            return redirect('dashboard:inicio')


class InversionistaList(LoginRequiredMixin, ListView):
    model = Inversionista
    template_name = 'dashboard/list_inver.html'
    context_object_name = 'objects'


class InversionistaDetail(LoginRequiredMixin, DetailView):
    model = Inversionista
    template_name = 'dashboard/inver_datail.html'
    context_object_name = 'objects'


class InversionistaUpdate(LoginRequiredMixin, UpdateView):
    model = Inversionista
    template_name = 'dashboard/update_form.html'
    form_class = InversionistaForm


class InversionistaDelete(LoginRequiredMixin, DeleteView):
    model = Inversionista
    success_url = reverse_lazy('dashboard:inver_list')
    template_name = 'dashboard/object_confirm_delete.html'


class ClienteList(LoginRequiredMixin, ListView):
    model = Cliente
    template_name = 'dashboard/list_cliente.html'
    context_object_name = 'objects'


class ClienteDetail(LoginRequiredMixin, DetailView):
    model = Cliente
    template_name = 'dashboard/detail_cliente.html'
    context_object_name = 'objects'


class ClienteUpdate(LoginRequiredMixin, UpdateView):
    model = Cliente
    template_name = 'dashboard/update_form.html'
    form_class = ClienteForm


class ClienteDelete(LoginRequiredMixin, DeleteView):
    model = Cliente
    success_url = reverse_lazy('dashboard:cliente_list')
    template_name = 'dashboard/object_confirm_delete.html'

gestionproyecto/templates/dashboard/cliente_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AñadirCliente</title>
</head>
<body>
 <form method="post">
     {% csrf_token %}
     {{form_cli.as_p}}
     {{form_user.as_p}}
     <button>Crear Cliente</button>
 </form>
</body>
</html>

gestionproyecto/templates/dashboard/dashboard.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
    <h2>Bienvenido {{nombre}}</h2>
</div>



{% endblock content %}

gestionproyecto/templates/dashboard/detail_cliente.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
     <div class="row">
    <div class="">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{objects.nombre_cliente}}</span>
          <p>{{objects.nit_cliente}}</p>
            <p>{{objects.tel_cliente}}</p>
            <p>{{objects.direc_cliente}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'dashboard:cliente_update' objects.id %}">Editar</a>
            <a href="{% url 'dashboard:cliente_delete' objects.id %}">Eliminar</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

gestionproyecto/templates/dashboard/inver_datail.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
     <div class="row">
    <div class="">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{objects.nombre}}</span>
          <p>{{objects.nit}}</p>
            <p>{{objects.telefono}}</p>
            <p>{{objects.direccion}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'dashboard:inver_update' objects.id %}">Editar</a>
    <a href="{% url 'dashboard:inver_delete' objects.id %}">Eliminar</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

gestionproyecto/templates/dashboard/iversionista_form.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
    <h2 class="center">Crear Inversionistas</h2>
    <form method="post">
     {% csrf_token %}
        {{form_inver.as_p}}
        {{form_user.as_p}}
     <button class="waves-effect waves-light btn">Crear Inversionista</button>
    </form>

</div>

{% endblock content %}

gestionproyecto/templates/dashboard/list_cliente.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
    <h2 class="center">Clientes</h2>



      <table>
        <thead>
          <tr>
              <th>Nombre Cliente</th>
              <th>Acciones</th>

          </tr>
        </thead>

        <tbody>
        {% for objetos in objects %}
            <tr>
                <td>{{objetos.nombre_cliente}}</td>
                <td>
                    <a href="{% url 'dashboard:cliente_detail' objetos.id %}">Ver</a> -
                    <a href="{% url 'dashboard:cliente_update' objetos.id %}">Editar</a> -
                    <a href="{% url 'dashboard:cliente_delete' objetos.id %}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
      </table>
    <div class="right">
        <a href="{% url 'dashboard:cliente_add' %}" class="btn-floating btn-large waves-effect waves-light red ">
            <i class="material-icons">add</i>
        </a>
    </div>

</div>
{% endblock content %}

gestionproyecto/templates/dashboard/list_inver.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
    <h2 class="center">Clientes</h2>
      <table>
        <thead>
          <tr>
              <th>Nombre Inversionista</th>
              <th>Acciones</th>

          </tr>
        </thead>

        <tbody>
        {% for objetos in objects %}
            <tr>
                <td>{{objetos.nombre}}</td>
                <td>
                    <a href="{% url 'dashboard:inver_detail' objetos.id %}">Ver</a> -
                    <a href="{% url 'dashboard:inver_update' objetos.id %}">Editar</a> -
                    <a href="{% url 'dashboard:inver_delete' objetos.id %}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
      </table>
    <div class="right">
        <a href="{% url 'dashboard:inver_add' %}" class="btn-floating btn-large waves-effect waves-light red ">
            <i class="material-icons">add</i>
        </a>
    </div>

</div>

{% endblock content %}

gestionproyecto/templates/dashboard/object_confirm_delete.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
    <div class="center">
        <form method="post">
     {% csrf_token %}
     <p>Esta seguro que quiere eliminar a "{{ object }}"?</p>
     <button class="waves-effect waves-light btn">Aceptar</button>
        <a href="{% url 'dashboard:inicio' %}" class="waves-effect waves-orange btn">Cancelar</a>
    </form>

    </div>

</div>
{% endblock content %}

gestionproyecto/templates/dashboard/update_form.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
    <h2 class="center">Editar</h2>
    <form method="post">
     {% csrf_token %}
     {{form.as_p}}
     <button class="waves-effect waves-light btn">Actualizar</button>
    </form>
</div>
{% endblock content %}