gestionproyecto/api/urls.py
from django.urls import path
from .views import (ClienteList, InversionistaList,
                    ProyectoView, TipoUsuario, ProyectoClienteView)
app_name = 'api'
urlpatterns = [
    path('clientes', ClienteList.as_view()),
    path('clientes/<int:pk>/', ClienteList.as_view()),
    path('inversionistas', InversionistaList.as_view()),
    path('inversionistas/<int:pk>/', InversionistaList.as_view()),
    path('proyectos', ProyectoView.as_view()),
    path('proyectos/clientes', ProyectoClienteView.as_view()),
    path('me', TipoUsuario.as_view()),
]

gestionproyecto/dashboard/urls.py
from django.urls import path
from .views import (index,
                    CrearCliente,
                    CrearInversionista,
                    InversionistaList,
                    ClienteList, ClienteDetail,
                    InversionistaDetail, InversionistaUpdate,
                    ClienteUpdate, InversionistaDelete,
                    ClienteDelete)
app_name = 'dashboard'
urlpatterns = [
    #path('register', register, name='register'),
    path('', index, name='inicio'),
    path('cliente-add/', CrearCliente.as_view(), name='cliente_add'),
    path('cliente-list', ClienteList.as_view(), name='cliente_list'),
    path('cliente/<int:pk>/', ClienteDetail.as_view(), name='cliente_detail'),
    path('edit/cliente/<int:pk>/', ClienteUpdate.as_view(), name='cliente_update'),
    path('delete/cliente/<int:pk>/', ClienteDelete.as_view(), name='cliente_delete'),
    path('inversionista-add', CrearInversionista.as_view(), name='inver_add'),
    path('inversionista-list', InversionistaList.as_view(), name='inver_list'),
    path('inver/<int:pk>/', InversionistaDetail.as_view(), name='inver_detail'),
    path('delete/inver/<int:pk>/', InversionistaDelete.as_view(), name='inver_delete'),
    path('edit/inver/<int:pk>/', InversionistaUpdate.as_view(), name='inver_update'),
]

gestionproyecto/gestionproyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('users', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('proyectos/', include('proyectos.urls')),
    path('api/login', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify', TokenVerifyView.as_view(), name='token_verify'),
    path('api/', include('api.urls')),
    path('', include('users.urls')),
]

gestionproyecto/proyectos/urls.py
from django.urls import path
from .views import (ProyectoList, CrearProyectoView,
                    ProyectoDetalle, ProyectoUpdate,
                    ProyectoDelete, FaseProyectoAdd,
                    FaseProyectoDetail, FaseProyectoUpdate,
                    FaseProyectoDelete)
app_name = 'proyecto'
urlpatterns = [
    path('', ProyectoList.as_view(), name='proyecto_list'),
    path('add-proyecto', CrearProyectoView.as_view(), name='add_proyecto'),
    path('proyecto/<int:pk>/', ProyectoDetalle.as_view(), name='detail_proyecto'),
    path('proyecto/edit/<int:pk>/', ProyectoUpdate.as_view(), name='edit_proyecto'),
    path('proyecto/delete/<int:pk>/', ProyectoDelete.as_view(), name='delete_proyecto'),
    path('fase-proyecto/add', FaseProyectoAdd.as_view(), name='add_fase'),
    path('fase-proyecto/<int:pk>/', FaseProyectoDetail.as_view(), name='detail_fase'),
    path('fase-proyecto/edit/<int:pk>/', FaseProyectoUpdate.as_view(), name='update_fase'),
    path('fase-proyecto/delete/<int:pk>/', FaseProyectoDelete.as_view(), name='delete_fase')

]

gestionproyecto/users/models.py
from django.db import models
from django.contrib.auth.models import User
from dashboard.models import (Empresa,
                              Cliente,
                              Inversionista)


class EmpresaUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.empresa)


class ClienteUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cliente)


class InversionistaUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    inversionista = models.ForeignKey(Inversionista, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.inversionista)

gestionproyecto/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
    {% block description %}{% endblock description %}
    <title>{% block title %}{% endblock title %}</title>
    {% block styles %}{% endblock styles %}
    {% block style_main %}{% endblock style_main %}
    {% block custom_style %}{% endblock custom_style %}
</head>
<body>
    {% block content %}{% endblock content %}
    {% block js %}{% endblock js %}
    {% block custom_js %}{% endblock custom_js %}

</body>
</html>

gestionproyecto/templates/base_materialize.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
{% endblock styles %}
{% block js %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery-1.11.2.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript">
     $(document).ready(function(){
         $('select').formSelect();
     });
    </script>
{% endblock js %}

gestionproyecto/templates/nav.html
{% load staticfiles %}

<nav>
    <div class="nav-wrapper">
        <a href="{% url 'dashboard:inicio' %}" class="brand-logo">Gestion Proyectos</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          {% if perms.users.add_empresauser %}
            <li><a href="{% url 'dashboard:cliente_list' %}">Clientes</a></li>
            <li><a href="{% url 'dashboard:inver_list' %}">Inversionistas</a></li>
            <li><a href="{% url 'proyecto:proyecto_list' %}">Proyectos</a></li>
          {% endif %}
      </ul>
    </div>
</nav>