gestionproyecto/api/urls.py
from django.urls import path
from .views import (ClienteList, InversionistaList,
                    ProyectoView, TipoUsuario, ProyectoClienteView)
app_name = 'api'
urlpatterns = [
    path('clientes', ClienteList.as_view()),
    path('clientes/<int:pk>/', ClienteList.as_view()),
    path('inversionistas', InversionistaList.as_view()),
    path('inversionistas/<int:pk>/', InversionistaList.as_view()),
    path('proyectos', ProyectoView.as_view()),
    path('proyectos/clientes', ProyectoClienteView.as_view()),
    path('me', TipoUsuario.as_view()),
]

gestionproyecto/gestionproyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('users', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('proyectos/', include('proyectos.urls')),
    path('api/login', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify', TokenVerifyView.as_view(), name='token_verify'),
    path('api/', include('api.urls')),
    path('', include('users.urls')),
]

gestionproyecto/proyectos/urls.py
from django.urls import path
from .views import (ProyectoList, CrearProyectoView,
                    ProyectoDetalle, ProyectoUpdate,
                    ProyectoDelete, FaseProyectoAdd,
                    FaseProyectoDetail, FaseProyectoUpdate,
                    FaseProyectoDelete)
app_name = 'proyecto'
urlpatterns = [
    path('', ProyectoList.as_view(), name='proyecto_list'),
    path('add-proyecto', CrearProyectoView.as_view(), name='add_proyecto'),
    path('proyecto/<int:pk>/', ProyectoDetalle.as_view(), name='detail_proyecto'),
    path('proyecto/edit/<int:pk>/', ProyectoUpdate.as_view(), name='edit_proyecto'),
    path('proyecto/delete/<int:pk>/', ProyectoDelete.as_view(), name='delete_proyecto'),
    path('fase-proyecto/add', FaseProyectoAdd.as_view(), name='add_fase'),
    path('fase-proyecto/<int:pk>/', FaseProyectoDetail.as_view(), name='detail_fase'),
    path('fase-proyecto/edit/<int:pk>/', FaseProyectoUpdate.as_view(), name='update_fase'),
    path('fase-proyecto/delete/<int:pk>/', FaseProyectoDelete.as_view(), name='delete_fase')

]

gestionproyecto/proyectos/models.py
from django.db import models
from django.shortcuts import reverse
from dashboard.models import Cliente

# Create your models here.


class Proyecto(models.Model):
    nombre_proyecto = models.CharField(max_length=50)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField(null=True)
    cliente = models.ForeignKey(Cliente, related_name='clientess', on_delete=models.CASCADE)
    descripcion = models.TextField(max_length=200)
    estado = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('proyecto:detail_proyecto', kwargs={'pk': self.pk})

    def __str__(self):
        return self.nombre_proyecto


class FaseProyecto(models.Model):
    nombre_fase = models.CharField(max_length=50)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    descripcion = models.TextField(max_length=200)
    estado = models.BooleanField(default=True)
    proyecto = models.ForeignKey(Proyecto, related_name='fases', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('proyecto:detail_fase', kwargs={'pk': self.pk})

    def __str__(self):
        return self.nombre_fase

gestionproyecto/proyectos/forms.py
from django import forms
from .models import Proyecto, FaseProyecto


class ProyectoForm(forms.ModelForm):
    class Meta:
        model = Proyecto
        fields = ('nombre_proyecto', 'fecha_inicio',
                  'fecha_fin', 'cliente', 'descripcion')


class FaseProyectoForm(forms.ModelForm):
    class Meta:
        model = FaseProyecto
        fields = (
            'nombre_fase',
            'fecha_inicio',
            'fecha_fin',
            'descripcion',
            'proyecto'
        )

gestionproyecto/proyectos/views.py
from django.shortcuts import render, Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (View, ListView, DetailView,
                                  UpdateView, DeleteView, CreateView)
from django.urls import reverse_lazy
from .models import Proyecto, FaseProyecto
from .forms import ProyectoForm, FaseProyectoForm


class ProyectoList(LoginRequiredMixin, ListView):
    model = Proyecto
    context_object_name = 'objects'
    template_name = 'proyectos/proyecto_list.html'


class CrearProyectoView(LoginRequiredMixin, CreateView):
    form_class = ProyectoForm
    model = Proyecto
    success_url = reverse_lazy('proyecto:proyecto_list')


class ProyectoDetalle(LoginRequiredMixin, View):
    # model = Proyecto
    # context_object_name = 'objects'
    # template_name = 'proyectos/proyecto_list.html'
    def get_object(self, pk):
        try:
            return Proyecto.objects.get(pk=pk)
        except Proyecto.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        context = {}
        proyecto = self.get_object(pk)
        context['proyecto'] = proyecto
        fases = FaseProyecto.objects.filter(proyecto=proyecto)
        context['fases'] = fases
        return render(request, 'proyectos/proyecto_detalle.html', context)


class ProyectoUpdate(LoginRequiredMixin, UpdateView):
    model = Proyecto
    form_class = ProyectoForm

class ProyectoDelete(LoginRequiredMixin, DeleteView):
    model = Proyecto
    success_url = reverse_lazy('proyecto:proyecto_list')
    template_name = 'proyectos/object_confirm_delete.html'


class FaseProyectoAdd(LoginRequiredMixin, CreateView):
    model = FaseProyecto
    form_class = FaseProyectoForm
    success_url = reverse_lazy('proyecto:proyecto_list')


class FaseProyectoDetail(LoginRequiredMixin, DetailView):
    model = FaseProyecto
    context_object_name = 'objects'
    template_name = 'proyectos/fase_detalle.html'


class FaseProyectoUpdate(LoginRequiredMixin, UpdateView):
    model = FaseProyecto
    form_class = FaseProyectoForm


class FaseProyectoDelete(LoginRequiredMixin, DeleteView):
    model = FaseProyecto
    success_url = reverse_lazy('proyecto:proyecto_list')
    template_name = 'proyectos/object_confirm_delete.html'

gestionproyecto/templates/proyectos/fase_detalle.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
     <div class="row">
    <div class="">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{objects.nombre_fase}}</span>
          <p>Fecha inicio: {{objects.fecha_inicio}}</p>
            <p>Fecha fin: {{objects.fecha_fin}}</p>
            <p>Descripcion: {{objects.descripcion}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'proyecto:update_fase' objects.id %}">Editar</a>
            <a href="{% url 'proyecto:delete_fase' objects.id  %}">Eliminar</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

gestionproyecto/templates/proyectos/faseproyecto_form.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
    <h2 class="center">Fases</h2>
    <form method="post">
     {% csrf_token %}
     {{form.as_p}}
     <button class="waves-effect waves-light btn">Crear Fase</button>
    </form>
</div>
{% endblock content %}

gestionproyecto/templates/proyectos/object_confirm_delete.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
    <div class="center">
        <form method="post">
     {% csrf_token %}
     <p>Esta seguro que quiere eliminar a "{{ object }}"?</p>
     <button class="waves-effect waves-light btn">Aceptar</button>
        <a href="{% url 'proyecto:proyecto_list' %}" class="waves-effect waves-orange btn">Cancelar</a>
    </form>

    </div>

</div>
{% endblock content %}

gestionproyecto/templates/proyectos/proyecto_detalle.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
     <div class="row">
    <div class="">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{proyecto.nombre_proyecto}}</span>
          <p>{{proyecto.fecha_inicio}}</p>
            <p>Fecha inicio proyecto:{{proyecto.fecha_fin}}</p>
            <p>Fecha fin proyecto: {{proyecto.descripcion}}</p>
            <p>Cliente: {{proyecto.cliente}}</p>
             {% if fases %}
            <h6>Fases:</h6>
        <ul>
            {% for fase in fases %}
                <li><a href="{% url 'proyecto:detail_fase' fase.id %}">{{fase.nombre_fase}}</a></li>
            {% endfor%}
        </ul>
    {% endif %}
        </div>
        <div class="card-action">
          <a href="{% url 'proyecto:edit_proyecto' proyecto.id%}">Editar</a>
         <a href="{% url 'proyecto:delete_proyecto' proyecto.id%}">Eliminar</a>
        <a href="{% url 'proyecto:add_fase'%}">crear fase</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

gestionproyecto/templates/proyectos/proyecto_form.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
    <h2 class="center">Proyectos</h2>
    <form method="post">
     {% csrf_token %}
     {{form.as_p}}
     <button class="waves-effect waves-light btn">Crear Proyecto</button>
    </form>
</div>
{% endblock content %}

gestionproyecto/templates/proyectos/proyecto_list.html
{% extends 'base_materialize.html' %}
{% load staticfiles %}

{% block content %}
{% include 'nav.html' %}
<div class="container">
    <h2 class="center">Proyectos</h2>
      <table>
        <thead>
          <tr>
              <th>Nombre Proyecto</th>
              <th>Cliente</th>
              <th>Acciones</th>

          </tr>
        </thead>

        <tbody>
        {% for objetos in objects %}
            <tr>
                <td>{{objetos.nombre_proyecto}}</td>
                <td>{{objetos.cliente}}</td>
                <td>
                    <a href="{% url 'proyecto:detail_proyecto' objetos.id %}">Ver</a> -
                    <a href="{% url 'proyecto:edit_proyecto' objetos.id %}">Editar</a> -
                    <a href="{% url 'proyecto:delete_proyecto' objetos.id %}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
      </table>
    <div class="right">
        <a href="{% url 'proyecto:add_proyecto' %}" class="btn-floating btn-large waves-effect waves-light red ">
            <i class="material-icons">add</i>
        </a>
    </div>

</div>
{% endblock content %}